### ISSUE TITLE
Diff quite hard to read - too much red

### ISSUE THREAD

**Issue by rofrol** [minwe/oceanic-next-jetbrains#2]
![oceanic-next](https://cloud.githubusercontent.com/assets/28787/9489161/4c14ce96-4bdf-11e5-94cd-c52491d7b0e9.PNG)

**Comment by minwe** [comment]
![2015-08-27 10 41 14](https://cloud.githubusercontent.com/assets/4370770/9511973/34c5c5ee-4caf-11e5-84b7-8f01dffa64a9.png)

I adjusted it to more like official theme `Darcula`.

**Comment by rofrol** [comment]
Thanks
