### ISSUE TITLE
Diff - hard to read html attribute and css, version="142"

### ISSUE THREAD

**Issue by rofrol** [minwe/oceanic-next-jetbrains#3]
![oceanic-next-diff-html-attribute](https://cloud.githubusercontent.com/assets/28787/9540357/35ede9ce-4d5e-11e5-90c1-9830d8d036c7.png)

![oceanic-next-diff-css](https://cloud.githubusercontent.com/assets/28787/9540437/12616336-4d5f-11e5-9a08-dfacf96eca28.png)

**Comment by minwe** [comment]
What about this?

![2015-08-28 3 07 42](https://cloud.githubusercontent.com/assets/4370770/9541012/c3451ca6-4d96-11e5-9996-ee893a26e967.png)
![2015-08-28 3 07 56](https://cloud.githubusercontent.com/assets/4370770/9541011/c33f690a-4d96-11e5-98c3-023d82a27afe.png)
![2015-08-28 3 08 23](https://cloud.githubusercontent.com/assets/4370770/9541013/c348a344-4d96-11e5-9de9-beab4646a8db.png)

**Comment by rofrol** [comment]
Much better. Backgrounds could be a little more darker for new lines.

**Comment by minwe** [comment]
Try to download the new version cb971c7b03874f1a9eca915c8b3c1b5c77460ae7.

**Comment by rofrol** [comment]
Much better, although it's too light for dark scheme. Compare it with darcula:

![webstorm-dracula](https://cloud.githubusercontent.com/assets/28787/9573368/f5df7716-4fbb-11e5-8467-41195fab0610.png)

![webstorm-oceanic-next-142](https://cloud.githubusercontent.com/assets/28787/9573371/fc7197f8-4fbb-11e5-96a4-d738eb050dfa.png)

**Comment by rofrol** [comment]
Any updates on this?

**Comment by minwe** [comment]
A little darker. The text is clear enough. I do not like too much darker. 

You can try https://github.com/minwe/oceanic-next-jetbrains/releases/tag/v0.2.1.

![2015-09-06 10 47 54](https://cloud.githubusercontent.com/assets/4370770/9702187/5bd0509a-5485-11e5-8a63-734eab2d52e2.png)

**Comment by rofrol** [comment]
Looks good :+1:

![oceanic](https://cloud.githubusercontent.com/assets/28787/9869144/0296f152-5b81-11e5-8b48-552836f2d863.PNG)
