### ISSUE TITLE
Not working on Webstorm 11 EAP

### ISSUE THREAD

**Issue by vagnervjs** [minwe/oceanic-next-jetbrains#6]
![screen shot 2015-10-01 at 1 59 36 pm](https://cloud.githubusercontent.com/assets/1696024/10227601/ad8de302-6844-11e5-9c72-942092b31452.png)

**Comment by minwe** [comment]
Try to install manually, just download and copy `Oceanic Next.icls` to:

```
~/Library/Preferences/WebStorm11/colors/
```

I'll check why the jar file not working on WS11 later.

**Comment by vagnervjs** [comment]
@minwe I had tried this before and it worked, thank you! :+1:

**Comment by minwe** [comment]
@vagnervjs 

WebStorm 11 Public preview, 143.267 seems fixed the bug, you can import  color scheme on the new version.

http://blog.jetbrains.com/webstorm/2015/10/webstorm-11-public-preview-143-267-fixes/
