### ISSUE TITLE
Underline is almost invisible

### ISSUE THREAD

**Issue by wasd171** [minwe/oceanic-next-jetbrains#7]
For example, writing

```
import Radium from 'radium'
```

gives `Default export is not declared in imported module`, but wavy underline under `Radium` is almost invisible

**Comment by minwe** [comment]
Do you mean the dashed underline like this?

![2016-02-29 4 38 07](https://cloud.githubusercontent.com/assets/4370770/13389478/3e84ea56-df03-11e5-8bd7-61d0b56954b6.png)

**Comment by wasd171** [comment]
Exactly!

Currently I am using `#FAC863` for such underline, it improves readability greatly

**Comment by minwe** [comment]
Could you tell me where is the option in IDE's `Preferences`.

There are too many color options and difficult to find it out.

Thanks.

**Comment by wasd171** [comment]
```
Preferences -> Editor -> Colors & Fonts -> General -> Errors and Warnings -> Weak Warning
```
