### ISSUE TITLE
`this` isn't italicized in es6 classes

### ISSUE THREAD

**Issue by morgs32** [minwe/oceanic-next-jetbrains#9]
my friend is on sublime and `this` is italicized in all classes. 
how can we add that formatting?
![image](https://cloud.githubusercontent.com/assets/1364795/19564563/f2b99240-96b1-11e6-91f5-0e0bc3d8291b.png)

**Comment by minwe** [comment]
<img width="898" alt="italic" src="https://cloud.githubusercontent.com/assets/4370770/19565498/9935add6-9719-11e6-9101-c1bf1f148e4b.png">

Check `Italic` under `Keyword`.
